### ISSUE TITLE
Docker scripts for deploying TSorage

### ISSUE THREAD

**Issue by Nico-Salamone** [cetic/tsorage#36]
In order to facilitate the deployment of TSorage, a Docker script for containerizing each service must be implemented. Here are the services that need to be containerized:
- Cassandra
- Ingestion module
- Processor module
- Hub module
- Kafka

**Comment by mgoeminne** [comment]
Plus kafka

Le ven. 25 oct. 2019 à 10:44, Nico Salamone <notifications@github.com> a
écrit :

**Comment by terence-bigtt** [comment]
Hi !

there is a very nice and easy to use packager for sbt, nativePackager
https://www.scala-sbt.org/sbt-native-packager/, that actually does more
than docker.

It's quite straightforward to use, juste pay attention to the resource
folder, it needs to be mapped to a specific location (related to the
Universe component, this is documented).

T.
PS: Cassandra is already containerized
T.


Le ven. 25 oct. 2019 à 10:44, Nico Salamone <notifications@github.com> a
écrit :

**Comment by mgoeminne** [comment]
A version using docker-compose has been proposed by @Nico-Salamone .
