### ISSUE TITLE
Add support for CoAP protocol 

### ISSUE THREAD

**Issue by mgoeminne** [cetic/tsorage#61]
In order to improve the support for IoT devices, a support should be provided for the [CoAP protocol](https://en.wikipedia.org/wiki/Constrained_Application_Protocol) .

**Comment by terence-bigtt** [comment]
This Java lib could be useful :
https://www.eclipse.org/californium/

**Comment by mgoeminne** [comment]
This feature is supported by ECS' collector tool, and will not be implemented here.

**Comment by mgoeminne** [comment]
Has been superseded by #66.
