### ISSUE TITLE
Error when transmitter communicates with the ingestor through HTTP

### ISSUE THREAD

**Issue by mgoeminne** [cetic/tsorage#93]
When the transmitter pushes messages to the ingestion through HTTP, it seems the ingestion does not receive these messages.

Tested with a Kubernetes cluster (dev environment)

**Comment by mgoeminne** [comment]
A first analysis reveals the problem is related to port access between Kubernetes containers.

**Comment by Sellto** [comment]
Yes, at the beginning the port was 127.0.0.1 but this port is unreachable when we are working with container. 
The ingestion have to listen on 0.0.0.0 to fix this issues. This value is used as default value in the helm chart.
